auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 3m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

  filesystem:
    directory: /loki/chunks

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 8760h
  retention_period: 8760h
  max_query_length: 8760h
  ingestion_rate_mb: 64               # default 4
  ingestion_burst_size_mb: 128        # default 6
  max_streams_per_user: 5000          # optional safeguard
  per_stream_rate_limit: 8MB          # default 3MB/sec


compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

