global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vault'
    metrics_path: "/v1/sys/metrics"
    scheme: http
    bearer_token_file: /shared/prometheus-token.txt
    static_configs:
      - targets: ['vault:8200']
        labels:
          vault_cluster: 'dev-cluster'
          vault_namespace: 'root'
          environment: 'local'
          job: 'vault'
